import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="text-6xl">
          Welcome to ArguBent!
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </h1>
      </main>
    </div>
  )
}


